<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="CryptoBots Viewer">

    <link rel="apple-touch-icon" sizes="180x180" href="<?=env('APP_VIEW_URL'); ?>/assets/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=env('APP_VIEW_URL'); ?>/assets/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=env('APP_VIEW_URL'); ?>/assets/favicon/favicon-16x16.png">
    <link rel="manifest" href="<?=env('APP_VIEW_URL'); ?>/assets/favicon/site.webmanifest">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('APP_VIEW_URL'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('APP_VIEW_URL'); ?>/assets/css/main.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">

</head>

<body>

    <header>
        <h1><?=$htmlTitle; ?></h1>
    </header>

    <main>
        <?=$content; ?>
    </main>

    <footer>
        CryptoBots is an NFT collection on Solana created by <a target="_blank" href="https://x.com/0xEDDB">Ed</a>

        <br />
        <hr />

        <small>
            This website is powered and maintained by <a target="_blank" href="https://hasmints.com">HasMints</a>
            <br />
            &copy; <?=date('Y'); ?>
        </small>
    </footer>

</body>

</html>
