
<div class="container">
    <div class="row">
        <?php foreach ($tokens as $token): ?>
            <div class="col col-md-3 col-6">
                <div class="card">
                    <div class="card-header">
                        <?=$token->name; ?>
                    </div>
                    <div class="card-content">
                        <a href="<?=$token->viewUrl; ?>">
                            <img class="img-fluid" src="<?=$token->imageV2; ?>" />
                        </a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>


